name: CML issue comment
on: issue_comment
jobs:
  cml:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Checkout Pull Request
      run: hub pr checkout ${{ github.event.issue.number }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - uses: iterative/setup-cml@v1
    - name: Display report
      env:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo "GitHub event ${{ github.event.issue.number }}"
        echo "Example CML comment on issue comment 6" >> report.md
        cml comment create --pr --publish report.md
