name: CML issue comment
on: issue_comment
jobs:
  cml:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.issue_comment.commit_id }}
    - uses: iterative/setup-cml@v1
    - name: Display report
      env:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo "GitHub ${{ github.event }}"
        echo "GitHub event ${{ github.event.issue_comment }}"
        echo "GitHub event ${{ github.event.issue_comment.comment_id }}"
        echo "Example CML comment on issue comment 5" >> report.md
        cml comment create --pr --publish --commit-sha=${{ github.event.issue_comment.comment_id }} report.md
