name: CML issue comment
on: issue_comment
jobs:
  cml:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{issue_comment.commit_id}}
    - uses: iterative/setup-cml@v1
    - name: Display report
      env:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo "Example CML comment on issue comment 2" >> report.md
        cml comment create --pr --publish report.md
