name: CML pull request
on:
  pull_request:
    types: [opened, edited]
jobs:
  cml:
    runs-on: ubuntu-latest
    steps:
    - name: Check for trigger word
      uses: khan/pull-request-comment-trigger@v1.1.0
      id: check
      with:
        trigger: "@launch:"
        reaction: rocket
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
    - uses: actions/checkout@v3
      if: steps.check.outputs.triggered == 'true'
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - uses: iterative/setup-cml@v1
      if: steps.check.outputs.triggered == 'true'
    - name: Display report
      if: steps.check.outputs.triggered == 'true'
      env:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo "Example CML comment on pull request 8" >> report.md
        cml comment create --pr --publish report.md
